[env]
"PROTOC_VER" = "3.6.1"

[tasks.build]
args = ["build"]

[tasks.test]
args = ["test"]

[tasks.gen-included-checked]
command = "protoc"
args = [
    "--rust_out=src/generated/checked",
    "--rust_opt=crate_name=crate,checked_size",
    "google/protobuf/any.proto",
    "google/protobuf/api.proto",
    "google/protobuf/descriptor.proto",
    "google/protobuf/duration.proto",
    "google/protobuf/empty.proto",
    "google/protobuf/field_mask.proto",
    "google/protobuf/source_context.proto",
    "google/protobuf/struct.proto",
    "google/protobuf/timestamp.proto",
    "google/protobuf/type.proto",
    "google/protobuf/wrappers.proto",
    "google/protobuf/compiler/plugin.proto"
]

[tasks.gen-included-unchecked]
command = "protoc"
args = [
    "--rust_out=src/generated/unchecked",
    "--rust_opt=crate_name=crate",
    "google/protobuf/any.proto",
    "google/protobuf/api.proto",
    "google/protobuf/descriptor.proto",
    "google/protobuf/duration.proto",
    "google/protobuf/empty.proto",
    "google/protobuf/field_mask.proto",
    "google/protobuf/source_context.proto",
    "google/protobuf/struct.proto",
    "google/protobuf/timestamp.proto",
    "google/protobuf/type.proto",
    "google/protobuf/wrappers.proto",
    "google/protobuf/compiler/plugin.proto"
]

[tasks.gen-sample]
command = "protoc"
args = [
    "--proto_path=protos",
    "--rust_out=examples/gen",
    "addressbook.proto"
]

[tasks.protoc-check.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
'''
$ErrorActionPreference='Stop'
if ($PSVersionTable.PSVersion.Major -lt 5) {
    Write-Host 'PowerShell version 5 or higher required for automatic protoc downloading and unpacking'
    exit 1
}

$ProtocUri = "https://github.com/protocolbuffers/protobuf/releases/download/v$($env:PROTOC_VER)/protoc-$($env:PROTOC_VER)-win32.zip"
$BuildPath = "$($env:CARGO_MAKE_WORKING_DIRECTORY)\build"
$ProtocPath = "$($env:CARGO_MAKE_WORKING_DIRECTORY)\build\protoc"

if (!(Test-Path -Path $ProtocPath)) {
    New-Item -Path $ProtocPath -ItemType "directory" | Out-Null
}

if (!(Test-Path -Path "$($ProtocPath)\bin\protoc.exe")) {
    Write-Host "Downloading $($ProtocUri) to $($BuildPath)"
    Invoke-WebRequest -OutFile "$($BuildPath)\protoc-$($env:PROTOC_VER)-win32.zip" -Uri $ProtocUri
    Expand-Archive -LiteralPath "$($BuildPath)\protoc-$($env:PROTOC_VER)-win32.zip" -DestinationPath $ProtocPath -Force
    Remove-Item "$($BuildPath)\protoc-$($env:PROTOC_VER)-win32.zip"
}
'''
]

[tasks.protoc-check.mac]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
'''
if [[ $(uname -m) -eq "x86_64" ]]; 
then
    OsArch="x86_64"
else
    OsArch="x86_32"
fi

ProtocUri='https://github.com/protocolbuffers/protobuf/releases/download/v'"$PROTOC_VER"'/protoc-'"$PROTOC_VER"'-osx-'"$OsArch"'.zip'
BuildPath="$CARGO_MAKE_WORKING_DIRECTORY"'/build'
ProtocPath="$CARGO_MAKE_WORKING_DIRECTORY"'/build/protoc'

if [ ! -d $BuildPath ] 
    then
        mkdir $BuildPath
fi

if [ ! -d $ProtocPath ] 
    then
        mkdir $ProtocPath
fi

if [ ! -f "$ProtocPath"'/bin/protoc' ] 
    then
        curl -L $ProtocUri -o "$BuildPath"'/protoc-'"$PROTOC_VER"'-osx-'"$OsArch"'.zip'
        unzip "$BuildPath"'/protoc-'"$PROTOC_VER"'-osx-'"$OsArch"'.zip' -d $ProtocPath
        rm "$BuildPath"'/protoc-'"$PROTOC_VER"'-osx-'"$OsArch"'.zip'
fi
'''
]

[tasks.protoc-check.linux]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
'''
if [[ $(uname -m) -eq "x86_64" ]]; 
then
    OsArch="x86_64"
else
    OsArch="x86_32"
fi

ProtocUri='https://github.com/protocolbuffers/protobuf/releases/download/v'"$PROTOC_VER"'/protoc-'"$PROTOC_VER"'-linux-'"$OsArch"'.zip'
BuildPath="$CARGO_MAKE_WORKING_DIRECTORY"'/build'
ProtocPath="$CARGO_MAKE_WORKING_DIRECTORY"'/build/protoc'

if [ ! -d $BuildPath ] 
    then
        mkdir $BuildPath
fi

if [ ! -d $ProtocPath ] 
    then
        mkdir $ProtocPath
fi

if [ ! -f "$ProtocPath"'/bin/protoc' ] 
    then
        curl -L $ProtocUri -o "$BuildPath"'/protoc-'"$PROTOC_VER"'-linux-'"$OsArch"'.zip'
        unzip "$BuildPath"'/protoc-'"$PROTOC_VER"'-linux-'"$OsArch"'.zip' -d $ProtocPath
        rm "$BuildPath"'/protoc-'"$PROTOC_VER"'-linux-'"$OsArch"'.zip'
fi
'''
]

[tasks.gen-move-included-checked]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
    'mv "src/generated/checked" "src/generated/checked.old"',
    'mkdir "src/generated/checked"'
]

[tasks.gen-move-included-checked.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
    'Rename-Item "src\generated\checked" "checked.old"',
    'New-Item "src\generated\checked" -ItemType "directory" | Out-Null'
]

[tasks.gen-move-included-unchecked]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
    'mv "src/generated/unchecked" "src/generated/unchecked.old"',
    'mkdir "src/generated/unchecked"'
]

[tasks.gen-move-included-unchecked.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
    'Rename-Item "src\generated\unchecked" "unchecked.old"',
    'New-Item "src\generated\unchecked" -ItemType "directory" | Out-Null'
]

[tasks.gen-move-sample]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
    'mv "examples/gen" "examples/gen.old"',
    'mkdir "examples/gen"'
]

[tasks.gen-move-sample.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
    'Rename-Item "examples\gen" "gen.old"',
    'New-Item "examples\gen" -ItemType "directory" | Out-Null'
]

[tasks.pre-gen]
description = "Moves old generated code to .old directories to be reverted or commited later"
dependencies = [
    "gen-move-included-checked",
    "gen-move-included-unchecked",
    "gen-move-sample",
]

[tasks.gen]
dependencies = [
    "protoc-check",
    "pre-gen"
]
run_task = "gen-flow"

[tasks.gen-flow]
dependencies = [
    "gen-included-checked",
    "gen-included-unchecked",
    "gen-sample",
]

[tasks.gen.windows]
env = { PATH = '${PATH};${CARGO_MAKE_WORKING_DIRECTORY}\build\protoc\bin;${CARGO_MAKE_WORKING_DIRECTORY}\target\debug' }

[tasks.gen.mac]
env = { PATH = '${PATH}:${CARGO_MAKE_WORKING_DIRECTORY}/build/protoc/bin:${CARGO_MAKE_WORKING_DIRECTORY}/target/debug' }

[tasks.gen.linux]
env = { PATH = '${PATH}:${CARGO_MAKE_WORKING_DIRECTORY}/build/protoc/bin:${CARGO_MAKE_WORKING_DIRECTORY}/target/debug' }

[tasks.build-gen]
dependencies = [
    "build",
    "gen"
]

[tasks.gen-revert]
dependencies = [
    "gen-revert-included-checked",
    "gen-revert-included-unchecked",
    "gen-revert-sample",
]

[tasks.gen-revert-included-checked]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
    'rm -rf src/generated/checked',
    'mv src/generated/checked.old src/generated/checked'
]

[tasks.gen-revert-included-checked.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
    'Remove-Item -Force -Recurse "src\generated\checked"',
    'Rename-Item "src\generated\checked.old" "checked"'
]

[tasks.gen-revert-included-unchecked]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
    'rm -rf "src/generated/unchecked"',
    'mv "src/generated/unchecked.old" "src/generated/unchecked"'
]

[tasks.gen-revert-included-unchecked.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
    'Remove-Item -Force -Recurse "src\generated\unchecked"',
    'Rename-Item "src\generated\unchecked.old" "unchecked"'
]

[tasks.gen-revert-sample]
script_runner = "/bin/bash"
script_extension = "sh"
script = [
    'rm -rf "examples/gen"',
    'mv "examples/gen.old" "examples/gen"'
]

[tasks.gen-revert-sample.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [
    'Remove-Item -Force -Recurse "examples\gen"',
    'Rename-Item "examples\gen.old" "gen"'
]

[tasks.gen-commit]
dependencies = [
    "gen-commit-included-checked",
    "gen-commit-included-unchecked",
    "gen-commit-sample",
]

[tasks.gen-commit-included-checked]
script_runner = "/bin/bash"
script_extension = "sh"
script = [ 'rm -rf "src/generated/checked.old"' ]

[tasks.gen-commit-included-checked.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [ 'Remove-Item -Recurse -Force "src\generated\checked.old"' ]

[tasks.gen-commit-included-unchecked]
script_runner = "/bin/bash"
script_extension = "sh"
script = [ 'rm -rf "src/generated/unchecked.old"' ]

[tasks.gen-commit-included-unchecked.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [ 'Remove-Item -Recurse -Force "src\generated\unchecked.old"' ]

[tasks.gen-commit-sample]
script_runner = "/bin/bash"
script_extension = "sh"
script = [ 'rm -rf "examples/gen.old"' ]

[tasks.gen-commit-sample.windows]
script_runner = "powershell"
script_extension = "ps1"
script = [ 'Remove-Item -Recurse -Force "examples\gen.old"' ]

[tasks.gen-git-add-included-checked]
command = "git"
args = [ "add", "src/generated/checked" ]

[tasks.gen-git-add-included-unchecked]
command = "git"
args = [ "add", "src/generated/unchecked" ]

[tasks.gen-git-add-sample]
command = "git"
args = [ "add", "examples/gen" ]

[tasks.gen-git-add]
dependencies = [
    "gen-git-add-included-checked",
    "gen-git-add-included-unchecked",
    "gen-git-add-sample",
]